name: Videos
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          comment_tag_name: VID
          channel_id: UCA_8UJgFWmFQ4byY0OaYxYA
          lang: en
          max_videos: 9
          card_width: 250
          commit_message: "Recent YouTube Videos"
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          base_url: https://ytcards.demolab.com/
          background_color: "#0d1117"
          title_color: "#ffffff"
          stats_color: "#dedede"
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
          readme_path: README.md
          output_only: false
          output_type: html
